#!/bin/sh

set -e

# cron script for mirroring /boot/efi to /boot/efi-mirror

# Only one simultanious instance allowed.
[ "$FLOCKER" != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :

rsync -qaAX --delete /boot/efi/ /boot/efi-mirror
